set_property PACKAGE_PIN B21 [get_ports sys_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property PACKAGE_PIN J21 [get_ports uart_rxd]
set_property PACKAGE_PIN M15 [get_ports uart_txd]

set_property PACKAGE_PIN F19 [get_ports acq]
set_property IOSTANDARD LVCMOS33 [get_ports acq]

# set_property PACKAGE_PIN P14 [get_ports sign_ccd]
# set_property IOSTANDARD LVCMOS33 [get_ports sign_ccd]

set_property IOSTANDARD TMDS_33 [get_ports lvds_ccd_p]
set_property PACKAGE_PIN F18 [get_ports lvds_ccd_p]
# set_property PACKAGE_PIN E18 [get_ports lvds_ccd_n]
#------------------ACM9767---------------------------------------
#DAC9767
set_property IOSTANDARD LVCMOS33 [get_ports WRTA]
set_property IOSTANDARD LVCMOS33 [get_ports ClkB]
set_property IOSTANDARD LVCMOS33 [get_ports WRTB]
set_property IOSTANDARD LVCMOS33 [get_ports ClkA]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[0]}]
set_property PACKAGE_PIN B16 [get_ports WRTB]
set_property PACKAGE_PIN B15 [get_ports ClkB]
set_property PACKAGE_PIN D17 [get_ports {DataB[13]}]
set_property PACKAGE_PIN C17 [get_ports {DataB[12]}]
set_property PACKAGE_PIN E16 [get_ports {DataB[11]}]
set_property PACKAGE_PIN D16 [get_ports {DataB[10]}]
set_property PACKAGE_PIN B17 [get_ports {DataB[9]}]
set_property PACKAGE_PIN B18 [get_ports {DataB[8]}]
set_property PACKAGE_PIN C18 [get_ports {DataB[7]}]
set_property PACKAGE_PIN C19 [get_ports {DataB[6]}]
set_property PACKAGE_PIN F16 [get_ports {DataB[5]}]
set_property PACKAGE_PIN E17 [get_ports {DataB[4]}]
set_property PACKAGE_PIN D20 [get_ports {DataB[3]}]
set_property PACKAGE_PIN C20 [get_ports {DataB[2]}]
set_property PACKAGE_PIN E19 [get_ports {DataB[1]}]
set_property PACKAGE_PIN D19 [get_ports {DataB[0]}]
set_property PACKAGE_PIN C15 [get_ports WRTA]
set_property PACKAGE_PIN C14 [get_ports ClkA]
set_property PACKAGE_PIN A14 [get_ports {DataA[13]}]
set_property PACKAGE_PIN A13 [get_ports {DataA[12]}]
set_property PACKAGE_PIN A16 [get_ports {DataA[11]}]
set_property PACKAGE_PIN A15 [get_ports {DataA[10]}]
set_property PACKAGE_PIN A19 [get_ports {DataA[9]}]
set_property PACKAGE_PIN A18 [get_ports {DataA[8]}]
set_property PACKAGE_PIN F14 [get_ports {DataA[7]}]
set_property PACKAGE_PIN F13 [get_ports {DataA[6]}]
set_property PACKAGE_PIN E14 [get_ports {DataA[5]}]
set_property PACKAGE_PIN E13 [get_ports {DataA[4]}]
set_property PACKAGE_PIN B13 [get_ports {DataA[3]}]
set_property PACKAGE_PIN C13 [get_ports {DataA[2]}]
set_property PACKAGE_PIN D15 [get_ports {DataA[1]}]
set_property PACKAGE_PIN D14 [get_ports {DataA[0]}]




